### ISSUE TITLE
Jack's beautiful strings: wrong algorithm

### ISSUE THREAD

**Issue by rakvium** [DmitrS/SlobodaTasks#2]
Your algorithm is wrong
`'AAaZzz'` should have value `153`, not `78`.

The main idea is to count the frequency of each letter, then assign the value 26 to the most frequent letter, 25 to the next, etc. If two letters are tied for most frequent, it doesn't matter which of them gets which value, since the sum will be the same. The python code below explains the solution pretty well.

**Comment by DmitrS** [comment]
Done. commit 8fc0a74421009b90822ed5ced7df09652ad14153
